<?xml version="1.0"?>
<robot name="simbot" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="$(find simulation)/urdf/mbot_base_gazebo.xacro"/>
    <xacro:include filename="$(find simulation)/urdf/sensors/imu_gazebo.xacro"/>
    <xacro:include filename="$(find simulation)/urdf/sensors/camera_gazebo.xacro"/>
    <xacro:include filename="$(find simulation)/urdf/sensors/lidar_gazebo.xacro"/>
    <xacro:include filename="$(find simulation)/urdf/actuators/aubo_i5.xacro"/>

    <!-- imu -->
    <xacro:property name="imu1_offset_x_n" value="0" />
    <xacro:property name="imu1_offset_y_n" value="0" />
    <xacro:property name="imu1_offset_z_n" value="0" />

    <xacro:property name="imu1_offset_r_n" value="0" />
    <xacro:property name="imu1_offset_p_n" value="0" />
    <xacro:property name="imu1_offset_y_n" value="0" />

    <xacro:property name="imu1_offset_x" value="0.35" />
    <xacro:property name="imu1_offset_y" value="0.2" />
    <xacro:property name="imu1_offset_z" value="${(base_height + imu_thickness) * 0.5}" />

    <xacro:property name="imu1_offset_r" value="0" />
    <xacro:property name="imu1_offset_p" value="0" />
    <xacro:property name="imu1_offset_y" value="0" />

    <joint name="imu1_joint" type="fixed">
        <origin xyz="${imu1_offset_x + imu1_offset_x_n}
                     ${imu1_offset_y + imu1_offset_y_n}
                     ${imu1_offset_z + imu1_offset_z_n}" 
                rpy="${imu1_offset_r + imu1_offset_r_n}
                     ${imu1_offset_p + imu1_offset_p_n}
                     ${imu1_offset_y + imu1_offset_y_n}" />
        <parent link="base_link"/>
        <child link="imu1_link"/>
    </joint>

    <xacro:imu_wheeltec prefix="imu1"/>

    <!-- Camera -->
    <xacro:property name="camera_offset_x" value="0.35"/>
    <xacro:property name="camera_offset_y" value="-0.2"/>
    <xacro:property name="camera_offset_z" value="${(base_height) * 0.5}"/>

    <joint name="camera_joint" type="fixed">
        <origin xyz="${camera_offset_x} ${camera_offset_y} ${camera_offset_z}" rpy="0 0 0" />
        <parent link="base_link"/>
        <child link="camera_link"/>
    </joint>

    <xacro:usb_camera prefix="camera"/>
    
    <!-- lidar -->
    <xacro:property name="lidar_more_height" value="0.05" />
    <xacro:property name="lidar_offset_x" value="-0.35" />
    <xacro:property name="lidar_offset_y" value="0" />
    <xacro:property name="lidar_offset_z" value="${base_height * 0.5 + lidar_more_height}" />

    <joint name="lidar_joint" type="fixed">
        <origin xyz="${lidar_offset_x} ${lidar_offset_y} ${lidar_offset_z}" rpy="0 0 0" />
        <parent link="base_link"/>
        <child link="laser_link"/>
    </joint>

    <xacro:rplidar prefix="laser"/>

    <!-- Arm -->
    <!-- <xacro:property name="arm_offset_x" value="0" />
    <xacro:property name="arm_offset_y" value="0" />
    <xacro:property name="arm_offset_z" value="${base_height * 0.5}" />

    <joint name="arm_joint" type="fixed">
        <origin xyz="${arm_offset_x} ${arm_offset_y} ${arm_offset_z}" rpy="0 0 0" />
        <parent link="base_link"/>
        <child link="arm_base_link"/>
    </joint>

    <xacro:aubo_i5 prefix="arm"/>

    <joint name="imu2_joint" type="fixed">
        <origin xyz="0 0 0" 
                rpy="0 0 0" />
        <parent link="wrist3_Link"/>
        <child link="imu2_link"/>
    </joint>

    <xacro:imu_wheeltec prefix="imu2"/> -->


    <xacro:mbot_base_gazebo/>

</robot>