<?xml version="1.0"?>
<robot name="simbot" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="$(find simulation)/urdf/mbot_base_gazebo.xacro" />
    <xacro:include filename="$(find simulation)/urdf/sensors/lidar_gazebo.xacro" />


    <xacro:property name="lidar_more_height" value="0.03" />
    <xacro:property name="lidar_offset_x" value="0" />
    <xacro:property name="lidar_offset_y" value="0" />
    <xacro:property name="lidar_offset_z" value="${base_height * 0.5 + lidar_more_height + 0.025}" />

    <!-- lidar -->
    <joint name="lidar_joint" type="fixed">
        <origin xyz="${lidar_offset_x} ${lidar_offset_y} ${lidar_offset_z}" rpy="0 0 0" />
        <parent link="base_link"/>
        <child link="laser_link"/>
    </joint>

    <xacro:rplidar prefix="laser"/>

    <xacro:mbot_base_gazebo/>

</robot>